#!/usr/bin/env python3
"""Render docs/compliance/dora-coverage.csv into README.md's DORA section.

The CSV is the source of truth: one row per DORA article (paragraph column empty) plus
paragraph-level rows for the technically substantive articles, plus Level 2 (RTS/ITS) rows.
README.md gets a generated, article-level summary between the two marker comments below, so
the prose and the sheet cannot drift apart.

    python3 docs/compliance/dora_readme.py           # rewrite README.md in place
    python3 docs/compliance/dora_readme.py --check   # exit 1 if README.md is out of date
"""
import collections
import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CSV_PATH = REPO / "docs/compliance/dora-coverage.csv"
README = REPO / "README.md"
START = "<!-- dora-coverage:start (generated by docs/compliance/dora_readme.py; edit the CSV, not this block) -->"
END = "<!-- dora-coverage:end -->"
REGULATION = "Regulation (EU) 2022/2554"

# Articles shown one per row. Everything else collapses into a grouped line, because it is
# addressed to authorities or is legal boilerplate rather than something a platform implements.
INDIVIDUAL = [str(n) for n in range(4, 31)] + ["45"]
GROUPS = [
    ("1–3", "Subject matter, scope, definitions", "Context",
     "Framing in [`docs/00-scope.md`](docs/00-scope.md): the notional tenant is a payment institution, which Art. 2 brings in scope"),
    ("31–44", "Oversight of critical ICT third-party providers", "Not applicable",
     "Between the ESAs and the providers; a firm still owes Art. 28 due diligence on any CTPP it uses"),
    ("46–56", "Competent authorities, cooperation, penalties", "Not applicable",
     "Addressed to authorities (in Ireland, the Central Bank of Ireland)"),
    ("57–64", "Delegated acts, review, amendments, entry into force", "Context",
     "Procedural; DORA applies from 17 January 2025"),
]


def load_rows():
    with CSV_PATH.open(newline="") as f:
        return list(csv.DictReader(f))


def link_paths(cell, limit=2):
    paths = [p for p in cell.split(";") if p]
    shown = ", ".join(f"[`{p}`]({p})" for p in paths[:limit])
    return shown + (f" +{len(paths) - limit}" if len(paths) > limit else "")


def render(rows):
    reg = [r for r in rows if r["instrument"] == REGULATION]
    summary = {r["article"]: r for r in reg if not r["paragraph"]}
    para_count = collections.Counter(r["article"] for r in reg if r["paragraph"])
    status_count = collections.Counter(summary[a]["lab_status"] for a in summary)

    out = [START, ""]
    out.append(
        f"Every article of DORA ({REGULATION}), with how this lab addresses it technically. "
        f"The full sheet, with {len(rows)} rows including paragraph-level detail and the Level 2 "
        "technical standards, is [`docs/compliance/dora-coverage.csv`](docs/compliance/dora-coverage.csv) "
        "(it renders as a table on GitHub and opens in any spreadsheet tool)."
    )
    out.append("")
    out.append(
        "Status words: **Implemented** (a mechanism exists *and* produced evidence), **Partial**, "
        "**Not met**, **Not applicable** (addressed to someone else), **Context**. "
        "\"Implemented\" never means a tenant is compliant. See [`docs/04-limitations.md`](docs/04-limitations.md)."
    )
    out.append("")
    out.append("Article-level count: " + ", ".join(f"{k} {v}" for k, v in sorted(status_count.items())) + ".")
    out.append("")
    out.append("| Art. | Title | Status | How it is addressed technically | Implemented by | Gaps / next task |")
    out.append("|---|---|---|---|---|---|")

    def row(r):
        n = para_count[r["article"]]
        detail = f" ({n} paragraph row{'s' if n != 1 else ''} in the sheet)" if n else ""
        nxt = "; ".join(x for x in (r["gaps"].replace(";", ", "), r["tasks"].replace(";", ", ")) if x)
        return (f"| {r['article']} | {r['title']} | {r['lab_status']} | {r['how_addressed']}{detail} | "
                f"{link_paths(r['implemented_by'])} | {nxt} |")

    out.append(f"| {GROUPS[0][0]} | {GROUPS[0][1]} | {GROUPS[0][2]} | {GROUPS[0][3]} | | |")
    for art in INDIVIDUAL:
        out.append(row(summary[art]))
        if art == "30":
            for g in GROUPS[1:2]:
                out.append(f"| {g[0]} | {g[1]} | {g[2]} | {g[3]} | | |")
    for g in GROUPS[2:]:
        out.append(f"| {g[0]} | {g[1]} | {g[2]} | {g[3]} | | |")
    out.append("")
    out.append("**Level 2 technical standards** (numbers to be verified on EUR-Lex before relying on them):")
    out.append("")
    out.append("| Instrument | Under Art. | Subject | Status |")
    out.append("|---|---|---|---|")
    for r in rows:
        if r["chapter"] == "Level 2":
            out.append(f"| {r['instrument']} | {r['article'].replace(';', ', ')} | {r['title']} | {r['lab_status']} |")
    out.append("")
    out.append("Gap IDs (G1–G24) refer to the gaps register in `docs/compliance/gaps.md` (PR #3); task IDs refer to "
               "[`docs/roadmap/`](docs/roadmap/README.md).")
    out.append("")
    out.append(END)
    return "\n".join(out)


def main():
    block = render(load_rows())
    text = README.read_text()
    if START not in text or END not in text:
        sys.exit(f"README.md is missing the marker comments:\n{START}\n{END}")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    new = head + block + tail
    if "--check" in sys.argv:
        if new != text:
            sys.exit("README.md DORA section is out of date: run python3 docs/compliance/dora_readme.py")
        print("README.md DORA section is up to date")
        return
    README.write_text(new)
    print(f"rendered {CSV_PATH.relative_to(REPO)} into README.md")


if __name__ == "__main__":
    main()
