rootUser: ENC[AES256_GCM,data:8OxrTUbcR0VHW834pPvqS42o,iv:m/r5t0IhyhCNdigoFnKa8MuiC2pKwNqORMrgLS8UKJo=,tag:zdl88mUGkDnyq5A8lNLWcw==,type:str]
rootPassword: ENC[AES256_GCM,data:gXQt5p3H+08SUJT7y3YoV/LUjETmxeSZYAL4p1q+SA==,iv:ZWU8geicuNET4u3ComQH0knXxzrNH4JpAKiYRrW1pGw=,tag:9pKhqjBXVjECdJnQQH1glw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUmFzNW5oZzhiOFpJejFC
            czF4NHl1cHFiOEpnTFZWS2l0K3VTSXNCa21nCnVadDFYWCtsd2hXNmh5bysySlIz
            ak5EdEVvY2tQaGxNMEgwb1F4K1J6RzgKLS0tIDZyU1JHemxWcUdDdmU2UElVTmZT
            dC9FS045RTRaVXRXTHcvU0ZRV3ZVaU0K9rjohOzgDl2tdzp3DcIoj5gFgFYoP2+3
            IFlNKA4sUttUsjXQ6oyaPKjoiZSXjO+8HqkZVqQl9PufIebou4QmMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-28T13:52:36Z"
    mac: ENC[AES256_GCM,data:N9hJVlHh7uVCqdYnRLyiiDjtJsMzMZDCoXXRmMbo6jhGlikNt9DJd5hE3tQ/xqPCChDMSbM1vnJ6zFCJvxGfHQOQIKkhUN39jPWh9/E1Qaan5bQmKpn4BCqWAZvcTib1iJ3jWyn94vxgQUDymT7ylswS9o8rXOo4vbHFpEUncT8=,iv:EC9iHE/i/FAM+AVc5+bhi9pDspRGI2t6r+KL0rs6tgg=,tag:qlHTlXNuIYkEp4+Q6qqXTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
