rootUser: ENC[AES256_GCM,data:JjFL22Hi7WCXDI7BhUrHa+ammjzxc6MF,iv:6ELgHMbgwOlKid/Fy4zGdXUCKam26LeYY2YL1S5ydlA=,tag:Hg80J7q+b3HfA0aFa9lluQ==,type:str]
rootPassword: ENC[AES256_GCM,data:xb2wp7pU0y+n2wW7NwOuAH8FDcQ9Elq6,iv:5yC0xwMXZFzi5GtgtXj4gzYXJwQOXe60CBIRN+XOYgM=,tag:B1+XPa8ybaP7OYvVw2xKnQ==,type:str]
sops:
    age:
        - recipient: age107ceqeyml5yqqxzs6uykdh0css8w4vggd4y09h862vzgn8sllvasus3er2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dW9wdE1wVHZJVlZ5NGVS
            Q2gwQ3gzbHFuQ1FUakpEOE1EQW02ZisvajJRCkxjNGs4WHJISmFLR283THF0TlJy
            YWEzQVdZYkRFaTFxaXluVzJKY3dJNUkKLS0tIEN6NnJ3TGtOYUhLWWl0bm9ET29N
            R0owaG0yQ2E1UWpuSUdBa2RJSGl6RTQKB1/w81qbFIkwXb3oQtE/kge3Qyy5YFnM
            J+Vd1Dn8+xrr2eumFHvl+KwZmj4pekz4ZRa2Da5Fp0nUt96fPN1Qtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:15:15Z"
    mac: ENC[AES256_GCM,data:O2Z02IZg+zNB8HN0AJ29w49M5+bhdxqwHPDAydE3jwuFvWf90HTZJ5PNPWaP3zmw0bJJKZP/FaosDb+xpkGDTR4QGokfC7ywGHDBHzg1cYymTFk+DiPc0kywi+Kbo3avQnA7A+U65KfoMJ1ad5AxBxJhCWUWw6JSvC+U45sjPYo=,iv:oV2/kiYfAJlPbzE/FSXOcUn8AwR5EmO0ouMuNqtEhgk=,tag:f0NcHuSKIB8XW5X7IS67PA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
