ldap_bind_password: ENC[AES256_GCM,data:b09kn1frU+nw7jrYXGwYDQagIyEcqSnGymKp5Cpft2o=,iv:mGlspnqUO4DNlOLGDMCWC9I5wvDDpXE/7boGDzf74n4=,tag:AoU6gBiR8+OMKcoK01CozQ==,type:str]
argocd_oidc_client_secret: ENC[AES256_GCM,data:iJSzFRRlVhg+eWuEs4YXdNGgYqBub0DWYaHZaLX/VQ==,iv:QvNanp9Dog6PuZCbqah/jsvPVP6w41ft2kPA+8/nnqQ=,tag:SA2k4M3Izs8O6uRKVflNdw==,type:str]
grafana_oidc_client_secret: ENC[AES256_GCM,data:KVf0dWctdTA9crjesaGQPDhTeWGmt26R+EpQcdo=,iv:vZyQKiU1UWFCrFQwbSnrgoB4F07xNYgR51l/5NS6Xf0=,tag:rrGLRWDTBSnyW1YIfmjpaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TEFFZzkwSnNPc3hSVzdO
            ckpIRjZZeU1BbkZNZHd1cGJDVHluaUhrWGdNCjZpWFdTamhwUnZ1OUZxbzA2QjNQ
            ODlCbVg2TDQ5a2hiVis3M0pLQ2l5T0kKLS0tIFNGMHVTeGhreFVoR1FCdm9jamF0
            VG9RYzdQQWp4TDlqWGJSQVpyeVNFWHMKzezYepUJfS1HEYkk+1RYyEPbwuAiAF3O
            RuBxe5a1BWQEinkwQD3acYk+gAzuVQnIPIs2JBFjJWOlO/fF3Iglxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-29T03:41:19Z"
    mac: ENC[AES256_GCM,data:NMbKHINZRQhw5YMrh6MjEKskpLUvW1A5qxioOzThRetPpzKuPbzCW2AzJ8Va78Ndx9VVyhPGdhiO7KnZnTCUYUmEjMQ4HtRxEz6X7v5Ot5ERySGMopfBP1LmJD2miMPOzhaA9D7pOdMc7YKsUr/QrR5yeVQlDf4Vr4wIVQSIqNE=,iv:0BB/ngD+G80bQzc6Lv5RqV0l8PEFKHcOt87v42Mqh8E=,tag:Oa6tUROYHAy9lgSsZaSbng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
