ldap_bind_password: ENC[AES256_GCM,data:zwpIKpw0RhPA+WYj8UJzbB3yN8QCKnJy+S9HciuTb80=,iv:B6ToVQ6WPRFK/cDG2KpX9ixgP1U9DGFAbJ+ueAjdAHA=,tag:ycK/9Uy/9c6nlmwfJ/MZMA==,type:str]
argocd_oidc_client_secret: ENC[AES256_GCM,data:4x3tLqkp9249aTo72EEUIlHRAH4q0QUG+8N+KCvNqA==,iv:6Vr/VNtITg81AUtauGBsEc/eQxa5StmoeTTjYhddTP8=,tag:3Sot9ylEzHc7g9mA5B4q9Q==,type:str]
grafana_oidc_client_secret: ENC[AES256_GCM,data:LHYYSbNYheKVMojHs5IUrqEhs1S2QHHSg0EiqnY=,iv:ZP+pzKOPW3nvFdw3+k1/ftBmstfgdI5AuYn5MqFlLHw=,tag:7qL6F+msSihzqbjSs37ILQ==,type:str]
alice_password: ENC[AES256_GCM,data:/ySTQ1u5TQ1utSlNQ3eN/InP1Oc=,iv:sWIx38n1MUNhrajMv+xz35lhQX/5Z6SQq09JvAlhTi0=,tag:ryyV/RUdKXRSl7N8Aw4QoA==,type:str]
bob_password: ENC[AES256_GCM,data:MWxoBnQuKIkjJ3hCx/na6CyUwZw=,iv:RiVL2MtTSOL7/7s0kloCM6v4GO71V9zVuHMorKVHJ58=,tag:wPxuwke+sWHlhP7p9VKoHg==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:oG/3saRk2WqCyvMlyKvV9c5YiX/bTDNJWwNY7g==,iv:dLpkuctoZiHjkrot/XhILkdM14UeCucjHHvk16umWLU=,tag:lipRA9Fm9qciJaZM6JnuMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcFhxTENMRzRISUFnUG5T
            NTR2TTIzUE5lZkVvVlUxNVRONmE1cHVLLzNVClRkUjJPM1l5THF5L3RUTUx4eUd0
            dE80SEVkYUNBY1VzempJM2xNSDlEcnMKLS0tIDdUM09Ga2Fwa0ovSjhyYWtiV3dn
            NXBybHN2ZEd4ODEzM21LNnFZM1JLelEKk5YS+etq0fh5aBypUYWtwOQm1fJm2RsS
            3NeJhDKf1/RulADOUe0xBnM0ukkjfNwWcQy8FZxy1q9wLAnhDOoS9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-29T04:06:18Z"
    mac: ENC[AES256_GCM,data:z1vb3UdTvsWgW3oqEmTM4e6oFzE0cP/eUuuG187zt4GGXAIv3MuwvrNxjQCeCDgPrFX4Qyzt6CxT02XxZkUlk4kB6+X7o4Um2GTCYC75YvfDqSVdDp2ud/T61wtaMIjJjoOyOAI+G7ZodojAW2IWPd4QHHrfSoOxW+6tSW6puis=,iv:HCwffVpkChNsp3TL98ygmMLqy4HNhBSlesn+QezYXNg=,tag:rY5wFGtKb6PIwWeb+JlUMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
