ldap_bind_password: ENC[AES256_GCM,data:0mSh25zb90yPAcZKrNhN8Wwlja/dMo5zg//qpn0Bjas=,iv:AJADsYNt4BmogUS6Nis0TwK00kpAiGZQlWQLyqrOums=,tag:Sq0ECQ1Hmbk1VmtYbQ6G0A==,type:str]
argocd_oidc_client_secret: ENC[AES256_GCM,data:M9XeAwqGZE/OBIP9mLtFJra+ZyzHJzE5xAC7lCFtzg==,iv:GmpEmlRk1cAj/aK+vEK5R0o0ELL9ZLjI6yZ9rwUVNjI=,tag:xQ+8jouOBwTVMpGBETrtQA==,type:str]
grafana_oidc_client_secret: ENC[AES256_GCM,data:mrXSndeLyKrVHh/+KnxolcUz+tI0AKyi7SEvrWk=,iv:UxMTpiP8xVPwLe3yv4bjE8dEtpwe8g/RnpSmkL9MRu0=,tag:5IL00BfhfBeQcBs9cogDgQ==,type:str]
alice_password: ENC[AES256_GCM,data:eZBQHA6aScNre+x/HrJO1gyDpRw=,iv:GW6gIAk4SUwl+i+Ep/UfmxxdKzh/eCfiV0esJZ6MIRE=,tag:n26JaSKA2kEEBMCTYc7MKw==,type:str]
bob_password: ENC[AES256_GCM,data:WK59UDDtb1ILb4qOijukbUAoEt4=,iv:kpiiWneIQLoCrPdRVWzvAPgqePicZFkC0bBY52pnnqU=,tag:e5G1+vhNWAt2N9SCiCGY+w==,type:str]
keycloak_admin_password: ENC[AES256_GCM,data:ogVf2gyCVbutQX3tSMJpm1gxzum1qIMSMNy6aA==,iv:EMR2v8+OoKejS0WGzsuSKLIouBV7lCXV+nMZAt5ZVps=,tag:W+DfXEP1phs/RBxcn8nB7g==,type:str]
minio_oidc_client_secret: ENC[AES256_GCM,data:dEwzMT3vOttgtNC0NVEYH91/8VWTrv6L,iv:26vPoljh3537GrJwAS35CjM8MZzIEeoeEXEgdsuqrpc=,tag:6h0DSYKu0Thm77liokrfFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndUZVYk4vTGNmaWdZaTRI
            aU5LTCtOaHhEQmMzUDA4QVhKRjlpNWUwWVFjClI0ajFsV0hhSnZLbWtSblEzTWd4
            ODV5cnd4L0Z3ZDlFdVVrM2FILzJWMW8KLS0tIE1Hb2dVem1hVXFEYktoTHpFa1By
            S1pDMFQxTjB0dlcwN1pBakFDb00rcjQK/yXZniGi1SzregxVEkH8P+uGBEUow3Sx
            i+PlM3D9tBeXs9sipN5CGukak0snAzgO3jNugOUbn3GpYs8XezY5uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-30T01:13:04Z"
    mac: ENC[AES256_GCM,data:ur/NOCJN/vkPYBu5TxiTI1eCBIiuT1jsHbKGVq3r/Mp3DpTG/O9gHe/8sFnom8mQ959lF3Y0bQ9ZTzh5LMx+kjjMw9x69uEm8QtfVrf3sDZbmAYNjR4sj+hZHFa+q9Lu7wITJ+TM+6zBfBJm+0+pUMoCfv2/m8m+TiPm0sAk080=,iv:JM8XgMVWsCSdw/G4ZTPY8ZhMzkGXlqUDUq+UIyqOWbI=,tag:KIGGfDYmvaKWHZmouAH5fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
