#!/usr/bin/env python3
"""Generates docs/evidence/report.md from manifest.yaml -- Phase 14's `make evidence`.

Was a stub ("evidence: not implemented yet") because nothing parsed evidence automatically;
docs/03-control-matrix.md stayed the one hand-maintained index. This doesn't replace that doc
(it's still the authoritative, hand-written control-to-requirement mapping) -- it's a generated
rollup one level down, grouping manifest.yaml's real artifact-to-tag mappings by framework so a
reader can see "what's actually evidenced, per framework" without reading collect.py's
by-control/ output folder-by-folder. Same "never hand-edit generated output" rule as
by-control/ itself: edit manifest.yaml, rerun.

Cross-references docs/evidence/integrity-chain.json's chain_head when present (Phase 20) so the
report states, not just how many controls are evidenced, but that the underlying files have a
real tamper-evidence property -- silently omitted, not asserted, if that file doesn't exist yet
(e.g. before `python3 docs/evidence/chain.py` has ever been run).
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

import yaml

EVIDENCE_DIR = Path(__file__).parent
MANIFEST_PATH = EVIDENCE_DIR / "manifest.yaml"
CHAIN_PATH = EVIDENCE_DIR / "integrity-chain.json"
OUTPUT_PATH = EVIDENCE_DIR / "report.md"

FRAMEWORK_NAMES = {
    "dora": "DORA",
    "nis2": "NIS2",
    "iso27001": "ISO 27001 Annex A",
    "nist80053": "NIST SP 800-53 Rev 5",
    "attack": "MITRE ATT&CK",
}


def main() -> int:
    manifest = yaml.safe_load(MANIFEST_PATH.read_text(encoding="utf-8"))
    artifacts = manifest["artifacts"]

    missing = [a["path"] for a in artifacts if not (EVIDENCE_DIR / a["path"]).exists()]
    if missing:
        print("ERROR: manifest references paths that don't exist:", file=sys.stderr)
        for p in missing:
            print(f"  - {p}", file=sys.stderr)
        return 1

    # framework -> control-id -> list of (artifact path, description)
    by_framework: dict[str, dict[str, list[tuple[str, str]]]] = defaultdict(lambda: defaultdict(list))
    for artifact in artifacts:
        for tag in artifact["tags"]:
            framework, control_id = tag.split(":", 1)
            by_framework[framework][control_id].append((artifact["path"], artifact["description"]))

    total_placements = sum(len(controls) for f in by_framework.values() for controls in f.values())

    lines = [
        "# Evidence report (generated)",
        "",
        "Generated by `docs/evidence/report.py` from the real artifact-to-control-tag mapping in "
        "`manifest.yaml` -- never hand-edit this file, edit `manifest.yaml` and run "
        "`python3 docs/evidence/report.py` again. `docs/03-control-matrix.md` remains the "
        "authoritative, hand-maintained control-to-requirement mapping; this is a generated "
        "rollup of what `manifest.yaml` says is evidenced, grouped by framework.",
        "",
        f"**{len(artifacts)} evidence artifacts, {total_placements} control-tag placements across "
        f"{len(by_framework)} frameworks.**",
        "",
    ]

    if CHAIN_PATH.exists():
        chain = json.loads(CHAIN_PATH.read_text(encoding="utf-8"))
        lines += [
            f"Evidence integrity: {chain['file_count']} files chained (sha256), "
            f"chain head `{chain['chain_head']}`, generated {chain['generated_at']} -- see "
            "`docs/evidence/integrity-chain.json` and `.github/workflows/evidence-integrity.yaml` "
            "for the signed, independently-verifiable anchor (Phase 20).",
            "",
        ]
    else:
        lines += [
            "Evidence integrity chain not yet generated -- run `python3 docs/evidence/chain.py` "
            "(Phase 20).",
            "",
        ]

    for fw in sorted(by_framework):
        fw_name = FRAMEWORK_NAMES.get(fw, fw)
        controls = by_framework[fw]
        lines.append(f"## {fw_name} (`{fw}:*`, {len(controls)} controls)")
        lines.append("")
        for control_id in sorted(controls):
            lines.append(f"### `{fw}:{control_id}`")
            for path, description in controls[control_id]:
                lines.append(f"- [`{path}`]({path}) -- {description}")
            lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"{len(artifacts)} artifacts, {total_placements} control-tag placements across "
        f"{len(by_framework)} frameworks -> {OUTPUT_PATH}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
