grafana_api_token: ENC[AES256_GCM,data:7IYqrWsdh8EIIizuCSgyDSR1bK8N+YciyY5k45/pmI9pQu53diwyT5LyAcDgvPUcgJBuIfrJaUWOkK2qMnEp51fPuCDNU2FLh2OH+ilXFS8m+xdj8E+fvC9Ba7q3Kffr8Oa2gZAZ,iv:Ba185KLjlgjeBoSEWunu4/NqG+2mxr2PD9Wn1pRNXxI=,tag:bcbEN1617NzyDSZXQImzKg==,type:str]
sops:
    age:
        - recipient: age107ceqeyml5yqqxzs6uykdh0css8w4vggd4y09h862vzgn8sllvasus3er2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTzY4K0VUL3pUa3I0OXJZ
            M1g3anJlYVAyM3plbEJvdjhQeEFjRnh4YmdJCmpZS0NTaCs3SXpZbUZ4MmlSVkRj
            cS83MzRnZ0ZJQ01JS0swVDgrWm9ZQkkKLS0tIFM4d2p0LzRaQmtkN3FJRjBGUUFQ
            RnFpcWxiNXljTEc4dFYrT0E3Umk3SGMK5FZx29IguiEce7Ha7kUoNqXyFSgGmf1y
            uAdTtxkxjS2NyRyoSfefc7CeYQefoGVKqg6MDGTf+0oduqaPCZY5ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:15:23Z"
    mac: ENC[AES256_GCM,data:CP0cK4zuqs2XyPWWu+FZMumTabnUgZO3cuQjM9JY30hqMMInxBZX9OjpOwiqzG8zGtGOeyhNlHpoI44Lfj3jwaH/BloO7+3Upk/e/u6dEX50Oef1FJSYpFuDZbJWH/O+U7XwaIv406GTezxpCvc8Vw0brQkZU+I6rnpT0piXeMs=,iv:jC43zf/qw8sftQ78nIWq7NujZorgqK6mwGaGbY+ItvQ=,tag:im+b21A2W+hTOHKYzv0xVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
