grafana_api_token: ENC[AES256_GCM,data:60A9stp+EBcaJ/b86dHStPc4pOgwqNHkhGsGCsMylhqgJ7JRPrxI0SoJsC0Ssw==,iv:PAo74p9D7/KPZqWGQaglhYmFONfTNn/llZ2rdBIOGu4=,tag:dleRhCCQ36IM/5WgKd5KAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTUVOM2g2U1NJNDlSY1Rl
            WmRJWkl3Tm0xakxCbEU2WWJ6NWZOOVNTamxVCmtyM1A1L2RiS0dYOWNQWUNHZTVK
            dXMrb0RiYWRMWUVPZnNXeHBsYlFDYTQKLS0tIEZNZHh2R05hR2FmTENZUHNKZFAx
            SFJkZ1FyaFBzcndLUml5ZncrUDF4VEkKiOnsOOGilqNE1IdkWrTEB6gwFz9TvgZB
            ikEC2niGRmOpCwfiqnYzXyTXB/VOyXqB7TYlhLMuRkpSJhPQ1DTQHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-29T13:09:56Z"
    mac: ENC[AES256_GCM,data:j/50vnnwQeDoENEV6nfFYqXWTqQ7BajJRa8kH1CNX8N/N7hJ/WtvjDbnJ4bohftFZdbFt7HxENqdbZELNokZU71SyLUrj3Loi6XfaVwWkIc2Z5kSMnY8Ch2+yiW+WzvpncmK2bIRe93htNnjaIr2+cxFVee4BJf9fzGHyfMxNQA=,iv:UAQgWER4ijvAToPF5ujqY38D3kzHIN3NxbXLmElIAZM=,tag:XE1+20nMBDqFFfoqsVCG6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
