mariadb_root_password: ENC[AES256_GCM,data:Svihq/1HKvwyTtyj0kXFFdtFBejAX6PJ,iv:JlccnFswh+G4FszqkW06qRN9K1sBJW5ckurOScbOkPQ=,tag:c3kIqUNGcKiR4g+Dqg/Pmw==,type:str]
glpi_db_password: ENC[AES256_GCM,data:wkKA2Ha319yMtzT78DOFZZ6crqvgv3mH,iv:bHMG3AWNSrRfzsufDvbaVnsOWB6obV2rFXvRQ+//3C4=,tag:jq1aUZ6yzSsaxAf9+9VZkQ==,type:str]
sops:
    age:
        - recipient: age107ceqeyml5yqqxzs6uykdh0css8w4vggd4y09h862vzgn8sllvasus3er2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSkpIVFlhMlRrQ3lSWmxI
            d1BUcGRJMXZqNGZ0TFJ3Y0JqdW9JNUVYTDJVCkRaRzlSeXJYWXlGWmowaHZNcjBJ
            YytscU4vSktUQytLeG1JR2g5elJqNG8KLS0tIGFPZmZIMTRMSFZUeUZBT1kyelR6
            c1VOWFcvbjdqTldFZzNGRG53TWlRZFUKlfgW+SoZhXch0hXGPe4yj+BOWlN1lASd
            PO01C5JioSxGr5tq7a4zSpNEet8sfB07x/pXI57c87+3nWYnHoDezA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:15:15Z"
    mac: ENC[AES256_GCM,data:hZreCqf3mm3twntk0ure9ayjq3jRGN/F7+gFdAzNSAIbTD843anYNC+pbEBqsDEpSdlqDpSGJeKZnIy5mtlvv2nCYbd7VD6EZgx63uAvi/Zok7/5Ropz9FL8poe9wz6QP/oNi6ptxHL51zl3y6BOpom8H/PiKShx7V1Y4cXdihU=,iv:KSRtiHS1MrVYlmi5gtK7l4b1xOv87dz7GJ4hhB7ishQ=,tag:sHSXH7ZYk+LVJ9B6n1cWPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
