mariadb_root_password: ENC[AES256_GCM,data:vDS5hDZRphKlC1BQUBQj3PwAbSt6gHeJ,iv:4wgBMnCsFNJ53dL0cF3cvfL0fnHe/RZeMDR4toQ0uoQ=,tag:8DX1elvzB4JbwJIaa3BR/A==,type:str]
glpi_db_password: ENC[AES256_GCM,data:t7KHclYLHI4C9bCJo+tWmqOM6WoUu9vU,iv:JDs1mgtS4R5VLdM1xjNzhcp/u94m8ukYnvJUhVBEFi4=,tag:Ua7NqiSWwXmkUV4cxWxJRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0R2NvZkFEWkRwSXVudVM4
            SDFLc0xmT1JrT3l6QWYwcUlHenYwQ0NPOHlrCjZhc2RKK2NPektGTmlhVlFHS3VI
            Nmk1Y3RpNnl0NG93WThiSVZ4QjVBOVUKLS0tIEtsRDMwSGpWcm5ySkhFS3o3aCtN
            NWVKNXZVU0ZCMmdzT3pWaTVhcUZDalUKZse0PhUGGyuWjhokPZFG8D8oZB8jEdc6
            ZslLIRCrHJRkJrC8sqmlZLawmJ6vLZhso6tVYhflV7jU1NDyT98RFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-29T19:37:23Z"
    mac: ENC[AES256_GCM,data:I0hq+Ex9PXV53nRtSIAaMTl/JO6wdIq/wJx7Rkeq2dTYBo9jmzhesVHRPQp8pgzAD7r6WjFbV8ZpZVQ6OdPXjLKJkz/+Qfqwm7u6G9U8goZfdADVLI1WPC5skbzIm9Zz49dkYeUW085wFIRL+A28158d7RQ4noOK86mDp2WH/fM=,iv:q6vO/1rc9tseHajXSHhjaaY4f5viG9hl6GMYVsv+qcw=,tag:/KTk3PMsVSar2eSNSklBLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
