mariadb_root_password: ENC[AES256_GCM,data:uny20jXgaCkeZ8VKGW+7AcniaVUt7z+L,iv:IOzM+RKfcgmCFiuU3e9E8TH3yRvBorJrYVfcsHqJEOY=,tag:I3HMPmRQJqaPv9LyHn7Alw==,type:str]
glpi_db_password: ENC[AES256_GCM,data:PokEWmnSSYD9ey/qlPbhAMmomRN1lnT8,iv:u4Cld80CcxZ2Uhbrg/Xc0RXmLoPK8bIvMqjV3/wVI+s=,tag:SsWfg/2YwCAOCZJzAZUsVQ==,type:str]
glpi_admin_password: ENC[AES256_GCM,data:p+aQ2igdzgWPlZRAGii5d9CF11H3Fd7D,iv:e86P6/3ykMnsRltNrpFAu6La2+EOuzpFwgrMJsw11VE=,tag:IGwqY5TCqabHfbg7IQYiSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUDlzU3R1czAxQmNPV090
            QUF5Wm1zaHlYcm02U1FOOXAxcENwY0RMUjBRCmRhVWR1emVreDBuamJwVFZQd3NR
            cXZGd1pMZVFjaThKMEt2QkcyZCt5dzQKLS0tIDh2alhLMUtTQ2hrMzJSZFJTclRq
            ZlNWSzE0bGZmeGdjVkxVU0szN0t1L28KNBJvbJmljKh/1TY+gnpH8g557CoGbM3/
            HgSbYsAzSb3bGSq+bdN+SeHkDSV3I6udGUJ1jU4nYK5HKnkqFfT5QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-29T18:18:34Z"
    mac: ENC[AES256_GCM,data:fGt0MOO4iguqWFNEcbwlAX8/fTvdkA0rJev4Qu4zVTt42vT43MFBRyv+7PzTXrZEGGcHBQvnkuQA/+Beg3vfT/g4hNdBG5fStxkRQu93ilrTGif3MvKii9vIINk9Evx2YvRoHBGshOTZarlJ2sj8OZ2dx2Zn1i7MTkNsW7XPC2M=,iv:oNZIuzW7F95MBNG/DPzUkBVh8Sd8Iqj5BAcKOwbv6gY=,tag:fGM5bU4eE/jl3VDgDVUVig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
