glpi_api_token: ENC[AES256_GCM,data:6SZ/ymJE2zm63zzr+GdrH5zR+yuYoI0f3JublDVsL51uq22C3BL+Og==,iv:TGUW6m3dV2OOC8/aZwZoYktV6XbE5u7WJ9xaTHqHaJc=,tag:lVEP61alOHPBdP9uSNa7ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScTYrYjFkZHp5VjhDUkYv
            WjQ2NEk0MUcrYXVQVE5BNEJZWGh1U3d6REdBCm5XSVlTRE8wVEdyWG5uS3U5UGly
            WVpia3RhTS9xcmdMTUVhbXBJb2xDSncKLS0tIFhLQ2V4Q3laUnFkRXVNa2hpSlhw
            T1E1K2ZkNVUzNnRNMzlYaHM4QTkyZzgKaKsWkCnTziItPzW/hUohvCRIdxHUdxsg
            iX/pi/uZWISj8F2Z9m1erRU3NoairjTGyNDjnAOfuQXCrRbOThPZVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wx4euyuda8a03qx674zxjv98e09symv20sfverxn4qrus6se5ucskemhl7
    lastmodified: "2026-07-29T19:36:20Z"
    mac: ENC[AES256_GCM,data:RvG2Fc+PrEeVug0eKQmuFTe4nu/ZAE8YGvrCPDZFGZvNFNGr/ZvfoeIDpKxTM4t7bn3vN6Ig8CcUQoNl0PTwmq0f5O+Vbv3GaocL1d1VSoF55IHpfIKPIl3LIOAoyQNv1YnwnZaemUPV0I7ahocgs6fs8DneiTZ6HqnVY6i4Vlc=,iv:UQYNg8jlU0h/pjQwt9ckdFdJUBtfLEOi4QZJc3jDq7I=,tag:rSBQ5AluFjqLigSngL6o3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
