glpi_api_token: ENC[AES256_GCM,data:qif6webS72y3thBDsnHiRteM/i6QXZyWe2yZGjTWi+68w2lOwaerGAV5O7peW3jqb5af1Fx6BFUM6ypqRWLUPdfj09059urRHyREa9Lu,iv:/Z8vIsiIey63kDWD2gtc3ji7ACEDXshbPzGWmsTAC+0=,tag:Ji9ixVNh08m3igxScpTmUg==,type:str]
sops:
    age:
        - recipient: age107ceqeyml5yqqxzs6uykdh0css8w4vggd4y09h862vzgn8sllvasus3er2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUDdUbytmRnY5MEkvSXls
            a3owS1V3VUJjZEQrUm4waisxMkNuNEZCcnpzCldqTWh4d1JIeEZQRm5Hb205R01k
            MWk1d09TcEpvLy81SU94OXdJeWtPYnMKLS0tIDYwVzZmaU5qUjB3OWFxUFVFY3Qv
            dDRUeE8zMzRoMk1kVW9iMW5PQUd3N2cKEVIENKlrds4BzHNnlhTd9R75PzqdKG0j
            EG5bT2g2bDH9dfHNn9ejs/LYrHQb2PvSq6IN5qFa1tjhmveEtDyvLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:15:23Z"
    mac: ENC[AES256_GCM,data:Q+Vil9Xde4NR/+ciRXDRFp+2UJIunV8AD+w46lYfxDuhujZyHUYMyeSNMhybQCniCD00tAmvJhrZFtpO0JqfzVRHuXtdZR+tppaDA2fc4pEQ7Oe1Dn+HJbU2fNMFpN6Jwjssp8ZvKDWz48oQHdKUEWYyMr/whiYS2t36lu+6elQ=,iv:XW2wu7ZhabvaExvfo4z4ap9LqbrkoY5kodbbY1VxnuM=,tag:1m1iJDzubB4diPXdmklLIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
