apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform
  source:
    repoURL: git@github.com:utility-soc/elastic-dora-blueprint.git
    targetRevision: master
    path: canary
  destination:
    server: https://kubernetes.default.svc
    namespace: canary
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
