apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drill-templates
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  source:
    repoURL: git@github.com:utility-soc/elastic-dora-blueprint.git
    targetRevision: master
    path: drills/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
